### ISSUE TITLE
[CQLReplicator on Glue] Discovered rows number from --state stats has less rows 

### ISSUE THREAD

**Issue by frozensky** [aws-samples/cql-replicator#101] opened 2024-01-31 23:52 UTC
after running cqlreplicator with `--state run`, `--tiles 12` and `--override-rows-per-worker 1500000`

I calculate the estimate total number of rows by multiply the number of tiles and Average primary keys per tile, it show the estimate number of primary keys (close to total number of rows) 
12 x 7,005,533 = 84,066,396

When I compare it to the Discovered rows from running cqlreplicator with `--state stats` which show  14007666
there is a big gap for it. 

I only see this when the table is big, for smaller table, the number is very close

Also the `Discovered rows` and `Replicated rows` don't match for this example, most of the previous run I did usually match
There is 0 `Write throttled events` during the data load

```
$ ./cqlreplicator --state run --tiles 12 --writetime-column usercollections --landing-zone s3://cqlrep-prd-1  --reg
ion us-west-1 --src-keyspace zap --src-table contentusercollectionmap --trg-keyspace zap --trg-table contentusercollectionmap --override-rows-per-worker 1500000  --inc-traffic
·······································································
[2024-01-31T12:16:43-08:00] OS: Darwin
[2024-01-31T12:16:43-08:00] Incremental traffic for the historical workload is enabled
[2024-01-31T12:16:43-08:00] Incremental period: 600 seconds
[2024-01-31T12:16:43-08:00] Starting discovery process...
[2024-01-31T12:16:43-08:00] TILES: 12
[2024-01-31T12:16:43-08:00] SOURCE: zap.contentusercollectionmap
[2024-01-31T12:16:43-08:00] TARGET: zap.contentusercollectionmap
[2024-01-31T12:16:43-08:00] LANDING ZONE: s3://cqlrep-prd-1
[2024-01-31T12:16:43-08:00] WRITE TIME COLUMN: usercollections
[2024-01-31T12:16:43-08:00] TTL COLUMN: None
[2024-01-31T12:16:43-08:00] ROWS PER DPU: 1500000
[2024-01-31T12:16:43-08:00] START REPLICATING FROM: 0 (0 is disabled)
[2024-01-31T12:16:43-08:00] Checking if the discovery job is already running...
[2024-01-31T12:16:47-08:00] Starting the discovery job...
[2024-01-31T12:17:02-08:00] Average primary keys per tile is 7005533
Starting Glue Jobs : [||||||||||||||||||||||||||||||||||||||||] 100.00% - COMPLETED
```

cqlreplicator stats WITHOUT define the target keyspaces and table 
```
$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1  --src-keyspace zap --src-table
 contentusercollectionmap
[2024-01-31T14:39:47-08:00] OS: Darwin
[2024-01-31T14:40:01-08:00] Discovered rows in zap.contentusercollectionmap is 14007666
[2024-01-31T14:40:01-08:00] Replicated rows in ks_test_cql_replicator.test_cql_replicator is 14007642
```

cqlreplicator stats WITH define the target keyspaces and table 
```
$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1  --src-keyspace zap --src-table
 contentusercollectionmap --trg-keyspace zap --trg-table contentusercollectionmap
[2024-01-31T15:51:09-08:00] OS: Darwin
[2024-01-31T15:51:25-08:00] Discovered rows in zap.contentusercollectionmap is 14007666
[2024-01-31T15:51:25-08:00] Replicated rows in zap.contentusercollectionmap is 14007642
```

**Comment by frozensky** [comment] 2024-02-01 01:18
looks like as long as my tiles is over 2, I see this behavior

**Comment by nwheeler81** [comment] 2024-02-01 04:40
1. This is the average number is not precise, it’s approximation, don’t use it for the data quality.2. I will look in the second issue: discovered rows != replicated rows. I might have to use 128 bits hashing function to avoid collisions in large datasets.On Jan 31, 2024, at 8:18 PM, Shaun Chan ***@***.***> wrote:﻿
looks like as long as my tiles is over 2, I see this behavior

**Comment by nwheeler81** [comment] 2024-02-01 15:23
@frozensky is it possible that rows were delete during the discovery stage?

**Comment by nwheeler81** [comment] 2024-02-01 15:28
@frozensky could you count rows inside each parquet file set by following path s3://cqlrep-prd-1/zap/contentusercollectionmap/primarykeys /tiles/tile_X_[head/tail]. I think you can use Amazon Athena or AWS Glue Notebook.

**Comment by frozensky** [comment] 2024-02-01 21:51
@nwheeler81 I understand the average number is not precise, but it's close to the # of discovered rows (for smaller table or when I run with 2 tiles)
when I start running with 4 or tiles, I see the # of discovered rows usually result in around half of the total rows in the table

I will try perform count in the s3 later.  I am testing different config to make sure I don't hit the write throttle

**Comment by nwheeler81** [comment] 2024-02-02 15:59
@frozensky I reproduced the issue with different `count` it's related to `keysDiscoveryProcess()` in `CQLReplicator.scala`. 
 `val groupedPkDF = primaryKeysDf.withColumn("group", abs(xxhash64(pkFinalWithoutTs.map(c => col(c)): _*)) % totalTiles).repartition(col("group"))` missing `.persist(StorageLevel.DISK_ONLY)` at the end.

// Let's generate 10M rows (uuid, int) and split by 10 tiles
```
import org.apache.spark.sql.{Row}
import java.util.UUID
import org.apache.spark.sql.types.{StructType, StructField, StringType, IntegerType}
import org.apache.spark.storage.StorageLevel

val rdd = sc.parallelize(1 to 10000000).map( i=> (UUID.randomUUID().toString, i))
val schema = new StructType().add(StructField("key", StringType, true)).add(StructField("col0", IntegerType, true))
val df = spark.createDataFrame(rdd.map(Row.fromTuple), schema)
val splitted = df.withColumn("group", abs(xxhash64(col("key"),col("col0"))) % 10).repartition(col("group"))
var sum:Long = 0

for (i <- 0 to 9) {
  val res:Long = splitted.where(col("group") === i).count()
  sum+=res
}

splitted.groupBy("group").count.show()

df.count() == sum // returns **false**
```

after I added `.persist(StorageLevel.DISK_ONLY)` returns `true`

**Comment by nwheeler81** [comment] 2024-02-02 22:13
@frozensky please check, I've merged the pr with the fix

**Comment by frozensky** [comment] 2024-02-02 22:41
I will pull the latest code and test later today and report back here.  Thank you

**Comment by frozensky** [comment] 2024-02-05 22:42
here is my test run, looks like I have to define the target keyspace and table also 
```
[ec2-user@ip-10-144-111-195 bin]$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --replication-stats-enabled

·······································································
[2024-02-05T22:41:07+00:00] OS: Linux
[2024-02-05T22:41:07+00:00] AWS CLI: aws-cli/2.14.5 Python/3.9.16 Linux/6.1.72-96.166.amzn2023.x86_64 source/x86_64.amzn.2023 prompt/off
[2024-02-05T22:41:07+00:00] Parameter ERROR: target table name is empty, must be provided empty or null
```

```
[ec2-user@ip-10-144-111-195 bin]$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --trg-keyspace personalcatalog --trg-table --replication-stats-enabled

·······································································
[2024-02-05T22:41:50+00:00] OS: Linux
[2024-02-05T22:41:50+00:00] AWS CLI: aws-cli/2.14.5 Python/3.9.16 Linux/6.1.72-96.166.amzn2023.x86_64 source/x86_64.amzn.2023 prompt/off
[2024-02-05T22:42:00+00:00] Discovered rows in personalcatalog.ztoken_meta is 5422477
[2024-02-05T22:42:00+00:00] Replicated rows in personalcatalog.--replication-stats-enabled is 2712272
```

**Comment by frozensky** [comment] 2024-02-06 00:12
Discovered rows in personalcatalog.ztoken_meta is 5422477 which is around half of total rows in the table

**Comment by nwheeler81** [comment] 2024-02-06 00:33
> Discovered rows in personalcatalog.ztoken_meta is 5422477 which is around half of total rows in the table

Any errors/warns related the discovery process?

**Comment by frozensky** [comment] 2024-02-06 02:11
I see some page timeout, but the replication looks complete. I can't tell since data is overwriting.  I do see total rows in aws keyspaces table is reasonable.  
 
```
2024-02-06 01:21:57,418 WARN [task-result-getter-2] scheduler.TaskSetManager (Logging.scala:logWarning(73)): Lost task 16.0 in stage 3630.0 (TID 18986) (10.144.106.38 executor 2): com.datastax.oss.driver.api.core.DriverTimeoutException: Timed out waiting for page 3
```

also, I don't see the detail similar to your stats example 
https://github.com/aws-samples/cql-replicator/tree/main/glue#get-migration-stats

```
[ec2-user@ip-10-144-111-195 bin]$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --trg-keyspace personalcatalog --trg-table --replication-stats-enabled

·······································································
[2024-02-06T02:05:54+00:00] OS: Linux
[2024-02-06T02:05:54+00:00] AWS CLI: aws-cli/2.15.17 Python/3.11.6 Linux/6.1.72-96.166.amzn2023.x86_64 exe/x86_64.amzn.2023 prompt/off
[2024-02-06T02:06:07+00:00] Discovered rows in personalcatalog.ztoken_meta is 5422477
[2024-02-06T02:06:07+00:00] Replicated rows in personalcatalog.--replication-stats-enabled is 5422477
```

**Comment by nwheeler81** [comment] 2024-02-06 14:49
> I see some page timeout, but the replication looks complete. I can't tell since data is overwriting. I do see total rows in aws keyspaces table is reasonable.
> 
> ```
> 2024-02-06 01:21:57,418 WARN [task-result-getter-2] scheduler.TaskSetManager (Logging.scala:logWarning(73)): Lost task 16.0 in stage 3630.0 (TID 18986) (10.144.106.38 executor 2): com.datastax.oss.driver.api.core.DriverTimeoutException: Timed out waiting for page 3
> ```
> 
> also, I don't see the detail similar to your stats example https://github.com/aws-samples/cql-replicator/tree/main/glue#get-migration-stats
> 
> ```
> [ec2-user@ip-10-144-111-195 bin]$ ./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --trg-keyspace personalcatalog --trg-table --replication-stats-enabled
> 
> ·······································································
> [2024-02-06T02:05:54+00:00] OS: Linux
> [2024-02-06T02:05:54+00:00] AWS CLI: aws-cli/2.15.17 Python/3.11.6 Linux/6.1.72-96.166.amzn2023.x86_64 exe/x86_64.amzn.2023 prompt/off
> [2024-02-06T02:06:07+00:00] Discovered rows in personalcatalog.ztoken_meta is 5422477
> [2024-02-06T02:06:07+00:00] Replicated rows in personalcatalog.--replication-stats-enabled is 5422477
> ```

I think, you're missing the targettable name `./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --trg-keyspace personalcatalog --trg-table --replication-stats-enabled`-> `./cqlreplicator --state stats --landing-zone s3://cqlrep-prd-1 --region us-west-1 --src-keyspace personalcatalog --src-table ztoken_meta --trg-keyspace personalcatalog --trg-table ***target_table_name*** --replication-stats-enabled`

**Comment by nwheeler81** [comment] 2024-02-06 14:53
@frozensky the large table is a candidate for a materialized view with the same primary key and one regular column that contains of the `updated_timestamp`

**Closed** 2024-02-07 18:59 UTC
Labels: documentation, question

**Comment by frozensky** [comment] 2024-02-07 19:15
I was missing `--tiles 4` when run with `--state stats`.  That's why the count of Discovered rows didn't loop thru everything.
